/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.fullerton.ecs.leoyang.CreatQuiz;

import edu.fullerton.ecs.leoyang.ModifyQuestions.*;
import edu.fullerton.ecs.leoyang.DeleteQuiz.PickQuizForDeleteQuiz;
import edu.fullerton.ecs.leoyang.Quiz;
import edu.fullerton.ecs.leoyang.ReadObjectToBinary;
import edu.fullerton.ecs.leoyang.StartQuiz.AnswerQuestion;
import edu.fullerton.ecs.leoyang.WriteObjectToBinary;
import edu.fullerton.ecs.leoyang.main;
import java.awt.Color;
import java.awt.Component;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.text.DecimalFormat;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JPanel;

/**
 *
 * @author 49876
 */
public class BackupQuestionMainWindow extends javax.swing.JInternalFrame {

    private JDesktopPane mainpane;
    private Quiz quiz,backupQuiz;
 private   int index;

    /**
     * Creates new form StartAnswer
     */
    public BackupQuestionMainWindow() {
        initComponents();
    }

    public BackupQuestionMainWindow(JDesktopPane mainpane, Quiz quiz, int index) {
        initComponents();
        this.mainpane = mainpane;
        this.quiz= quiz;
        this.index= index;
        ReadObjectToBinary reader = new ReadObjectToBinary();
        backupQuiz = reader.readFromBinary("BackUpQuestion.bin");
        
                for(int i =0; i< backupQuiz.getQCount(); i++)
         {
                jTabbedPane1.addTab(Integer.toString(i+1), new ShowBackupQuestions(backupQuiz.clone(),i,mainpane, quiz, this));
         }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();

        jTabbedPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jTabbedPane1.setMaximumSize(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTabVisibleToFalse(int index) {
        jTabbedPane1.getTabComponentAt(index).setVisible(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
