/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.fullerton.ecs.leoyang.StartQuiz;

import edu.fullerton.ecs.leoyang.Quiz;
import edu.fullerton.ecs.leoyang.main;
import java.awt.Color;
import java.awt.Component;
import java.beans.PropertyVetoException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JPanel;

/**
 *
 * @author 49876
 */
public class StartAnswer extends javax.swing.JInternalFrame {

    private JDesktopPane mainpane;
    private Quiz quiz;
    private AnswerQuestion[] a;
    long x, y;

    /**
     * Creates new form StartAnswer
     */
    public StartAnswer() {
        initComponents();
    }

    public StartAnswer(JDesktopPane mainpane, Quiz quiz) {
        initComponents();
        this.mainpane = mainpane;
        this.quiz = quiz;
        a = new AnswerQuestion[quiz.getMaxQuestion()];
        for (int i = 0; i < quiz.getMaxQuestion(); i++) {
            if (quiz.getType(i).equals("Short Answer")) {
                a[i] = new AnswerQuestion(quiz.clone(), i, mainpane);
                //a.setSize(mainpane.getSize());
                jTabbedPane1.addTab(Integer.toString(i + 1), new AnswerQuestion(quiz.clone(), i, mainpane));
            } else {
                a[i] = new MultiplyQuestion(quiz.clone(), i, mainpane);
                //a.setSize(mainpane.getSize());
                jTabbedPane1.addTab(Integer.toString(i + 1), new MultiplyQuestion(quiz.clone(), i, mainpane));
            }

        }
        x = System.currentTimeMillis();
        back.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        totalPointsEarned = new javax.swing.JLabel();
        totalPoints = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        percentage = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        submit = new javax.swing.JButton();
        back = new javax.swing.JButton();

        jTabbedPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jTabbedPane1.setMaximumSize(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        totalPointsEarned.setPreferredSize(new java.awt.Dimension(50, 100));

        totalPoints.setPreferredSize(new java.awt.Dimension(50, 100));

        time.setPreferredSize(new java.awt.Dimension(50, 100));

        percentage.setPreferredSize(new java.awt.Dimension(50, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(totalPointsEarned, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(totalPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {time, totalPoints, totalPointsEarned});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(percentage, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(totalPointsEarned, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {time, totalPoints, totalPointsEarned});

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        back.setText("Main Page");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(submit, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(back, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here: for(int i =0; i< quiz.getMaxQuestion(); i++)
        double total = 0;
        boolean isFinish = true;
        AnswerQuestion[] c = new AnswerQuestion[jTabbedPane1.getComponentCount()];
        donext:
        for (int i = 0; i < jTabbedPane1.getComponentCount(); i++) {
            a[i] = (AnswerQuestion) jTabbedPane1.getComponentAt(i);

           // if ((c[i].answer.getText().equals(""))) {
             if ((a[i].getAnswer().equals(""))) {
                isFinish = false;
                break donext;
            }
        }

        if (isFinish) {
            y = System.currentTimeMillis();
            for (int i = 0; i < jTabbedPane1.getComponentCount(); i++) {
                if (!a[i].getAnswer().equals("")) {
                    if (!quiz.checkAnswers(i, a[i].getAnswer())) {
                        jTabbedPane1.setForegroundAt(i, Color.red);

                    } else if (quiz.checkAnswers(i, a[i].getAnswer())) {
                        total += quiz.getPoint(i);
                    }
                }
                //a[i].answer.setEnabled(false);
                a[i].showAnswer(quiz.getAnswer(i));
            }
            DecimalFormat df = new DecimalFormat("0.00");

            totalPointsEarned.setText("You earned: " + df.format(total));
            totalPoints.setText("Total Points: " + df.format(quiz.getTotalPoints()));
            double t = (total / quiz.getTotalPoints()) * 100;
            percentage.setText("Final Grade:" + df.format(t) + "%");
            time.setText("You toke: " + Long.toString((y - x) / 1000) + "s");;
            submit.setVisible(false);
            back.setVisible(true);

        }
        if (!isFinish) {
            percentage.setText("Answer all the question!!");
        }


    }//GEN-LAST:event_submitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        main.a.enableMenuBar();
        this.dispose();
    }//GEN-LAST:event_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel percentage;
    private javax.swing.JButton submit;
    private javax.swing.JLabel time;
    private javax.swing.JLabel totalPoints;
    private javax.swing.JLabel totalPointsEarned;
    // End of variables declaration//GEN-END:variables
}
